import { Metadata } from "next"
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js 14 Learning project",
    template: "%s | Ashok"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: "lightblue",
          padding: "1rem"
        }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{
          backgroundColor: "wheat",
          padding: "1rem"
        }}>
          <p>Footer</p>
        </footer>
      </body>

    </html >
  )
}
